### ISSUE TITLE
infinite loop probably

### ISSUE THREAD

**Issue by themabus** [maestun/alis#12]
Hello! 
There appears to be problem with some DOS titles, that previously booted up, e.g.: Metal Mutant, Targhan, Ishar 2, now hanging on launch. I think the issue was introduced on Feb 18, by replacing 'usleep(2000)' with a more complex construction in 'alis.c'

**Comment by Cosmicore** [comment]
Hello, I have tested Metal Mutant and Targhan and both of these games work for me. My version is compiled for Windows.

What platform do you have Alis compiled for? Do the games hang before the Silmarils splash screen or later?

**Comment by themabus** [comment]
I'm on Windows too, Msys2. Although it's a bit dated, maybe that's why. 
For instance with that updated delay routine either Targhan from here will freeze before logo:
https://archive.org/download/Various_DOS_Abandonware_Ark

`main.io [0261b4:ffac]: 0x02c472:

[INFO]  cbz24

[INFO]  0x000085

[INFO]

main.io [0261b4:ffac]: 0x02c4fb:

[INFO]  ceval

[INFO]  oeval

[INFO]  olocb

[INFO]  0x1b65

[VERBOSE]  [01 <= 027d19]

[INFO]  oegal

[INFO]  oimmb

[INFO]  0x00

[INFO]  ofin

[INFO]  [ = 0]

[INFO]

main.io [0261b4:ffac]: 0x02c504:

[INFO]  cbz24

[INFO]  0x000006

[INFO]

main.io [0261b4:ffac]: 0x02c50e:

[INFO]  cstop

[INFO]

-- CSTOP --`

**Comment by Cosmicore** [comment]
Tried both versions that are posted there. They work fine for me.

Give more information, please. What version, configuration, compiler? How did you solve the POSIX compatibility problem? Did you add missing libraries/functions? From where?

Until the problem is solved I would suggest to try Cygwin as well.

An extended log to the issue:
```
RUNNING main.io [00, 01]
main.io [00002e]000000: 29: cdim ###  0x0010 0x00 0x02
.....
main.io [000358]00032a: 14: cbz24 ###  0x000085   // main.io [0261b4:ffac]: 0x02c472:
main.io [0003e1]0003b3: 1f: ceval ###
      --> [0003e2]0003b4: 38: oeval ###
      --> [0003e3]0003b5: 06: olocb ###  0x1b65
      --> [0003e6]0003b8: 4a: oegal ###
      --> [0003e7]0003b9: 00: oimmb ###  0x00
      --> [0003e9]0003bb: 3a: ofin ###  [ = 0]
main.io [0003ea]0003bc: 14: cbz24 ###  0x000006   // main.io [0261b4:ffac]: 0x02c504:
main.io [0003f4]0003c6: 42: cstop ###
-- CSTOP --
main.io [00318c]00315e: 1f: ceval ###   // main.io [0261b4:ffac]: 0x02f2a6:
      --> [00318d]00315f: 38: oeval ###
      --> [00318e]003160: 00: oimmb ###  0x00
      --> [003190]003162: 40: opushacc ###
      --> [003191]003163: 06: olocb ###  0x1b6c
      --> [003194]003166: 4a: oegal ###
      --> [003195]003167: 00: oimmb ###  0x03
      --> [003197]003169: 44: oor ###
      --> [003198]00316a: 36: opile ###
      --> [003199]00316b: 3a: ofin ###  [ = 0]
main.io [00319a]00316c: 14: cbz24 ###  0x000003
```

Does it hang after executing the `cstop` command? No more lines/commands in your log? Or are all these commands repeated over and over again? Where does it go after `cstop` then (instead of 0x02f2a6)?

**Comment by skruug** [comment]
@themabus looks like you were right, there was uninitialized struct timeval used to calculate how long to sleep before executing next command...
Please try latest version if your issue is fixed.

**Comment by themabus** [comment]
Seems to be working now. Thank you.

**Comment by Cosmicore** [comment]
Interestingly, the manifestation of the consequences of this “uninitialized struct timeval” really depended on the compiler.

Just compiled the previous version with Mingw, and indeed sometimes after `cstop` everything hung. But there are no such consequences for Cygwin.

I tried these compilers:

**GCC 11.3.0 x86_64-pc-cygwin** c:\cygwin64\bin\gcc.exe
* Works fine.

**GCC 11.3.0 x86_64-w64-mingw32** c:\cygwin32\bin\x86_64-w64-mingw32-gcc.exe
* Needs termios.h, mman.h in sys; added dirent.h for 'd_type', DT_REG
* A problem after `cstop`.

**GCC 12.2.0 x86_64-w64-mingw32 (ucrt64)** c:\msys64\ucrt64\bin\gcc.exe
* Needs termios.h, mman.h in sys; added dirent.h for 'd_type', DT_REG
* A problem after `cstop`.

The new version works fine with all of them. Thank you!
