### ISSUE TITLE
[Ishar 1] [Amiga/AGA] Palette problem on language selection screen

### ISSUE THREAD

**Issue by vanfanel** [maestun/alis#23]
The game itself seems to run perfectly, other than this minor palette problem on the language selection screen:

![ishar_palette_bug](https://github.com/user-attachments/assets/c547befe-48a9-4c85-bb7a-ae3133b98d3c)

The PC-DOS/VGA version is not affected at all, only the Amiga AGA version seems to be affected.

**Comment by skruug** [comment]
16 color images on AGA amiga used 9 bit palette instead of correct 12 bit. Fixed!

**Comment by vanfanel** [comment]
Looks perfect now! :)
