### ISSUE TITLE
[Question] What's the tick rate of the Alis engine?

### ISSUE THREAD

**Issue by vanfanel** [maestun/alis#26]
Hi again,

On the Amiga and DOS, Ishar games do smooth fade-in/fade-out transitions (I still have them on FPGA-based implementations of these systems).
That means the games draw their frames at a rate that matches the screen refresh, which on the Amiga was usually 50.xxxxHz (PAL) or 60.xxxxHz (NTSC).
No exact idea about the PC, but the games run in 320x200 at 70Hz, so 70 or 35 ticks-per-second is my guess (doesn't mean the game will always refresh the screen 70 times per second, talking about "ticks" here: Ishar games are very slow-paced and sometimes a frame can take more than a second to be presented to screen).

Now, what is the framerate / tick rate of the Alis engine?
I have searched the sources and couldn't get a clear answer.

I do my Alis builds with added `SDL_RENDERERE_PRESENTVSYNC` flag to `SDL_CreateRenderer()` which should ensure the same smooth transitions provided I set a matching physical video mode refresh rate, which is very easy to do on Wayland :)

Thanks!

PD: I know I repeat myself, but really, this engine is so utterly incredible for me! I'm having a LOT of run with it, no modern game can give me anything near it, the Silmarils games are pure magic.

**Comment by skruug** [comment]
Hi, alis was based on Atari ST PAL version, so its framerate is 50hz. In future we may change it to be platform dependent.
It can be changed in 'image.c' #define FRAME_TICKS (1000000 / 50)

**Comment by vanfanel** [comment]
> Hi, alis was based on Atari ST PAL version, so its framerate is 50hz. In future we may change it to be platform dependent. It can be changed in 'image.c' #define FRAME_TICKS (1000000 / 50)

Ah, that's so good to know! Thanks! :)
