### ISSUE TITLE
Possible ScummVM integration?

### ISSUE THREAD

**Issue by neuromancer** [maestun/alis#3]
I know this implementation of this game engine is still a work in progress, but I'm wondering if it makes sense to plan a future integration as a ScummVM engine (which already have a good number of RPGs). ScummVM also provides a number of image/sound decoders from old games which helps to reduce code duplication.

**Comment by maestun** [comment]
Hi, yes we've been discussing a bit with the ScummVM team, and that is something that could be possible in the future.
