### ISSUE TITLE
[Ishar 1] [Amiga / AGA] Snoring effect in tavern doesn't stop after sleeping

### ISSUE THREAD

**Issue by vanfanel** [maestun/alis#38]
When sleeping on the tavern, a snoring effect plays, however it doesn't stop after that, and keep sounding until you exit the tavern.
On the original engine, the snoring effect stops as soon as the sleeping message disappears.

**Comment by Cosmicore** [comment]
Thank you! Added to Todo (will be updated in the repo on the next commit).

**Comment by skruug** [comment]
Should be fixed in latest version.

**Comment by vanfanel** [comment]
> Should be fixed in latest version.

Yes, sir! All correct now with the snoring! :D
