### ISSUE TITLE
Transarctica / Artic baron, "transalogo.io" missing?

### ISSUE THREAD

**Issue by DerBesserwisser** [maestun/alis#7]
Hello,
hope its ok to address this via an issue:
I am on a Manjaro system and built the code successfully. I copied the content from my original (german, but recalling the text on the box beeing in three languages it probably does not matter) floppy discs to a dir and started alis via "alis path-to-transa-files". But after a few seconds I get the warning "Failed to open script at path 'transalogo.io'. I can't find the file on my discs

Is this a file that should be in the data directory ?

Thank you kindly

**Comment by skruug** [comment]
Hi, it looks like missing path separator. Try to run it again but with path separator at the end of path.
Something like "alis /path/to/transarctica/".

**Comment by skruug** [comment]
Fixed, now you can use path argument with or without path separator.
p.s. Thanks for testing and reporting bugs. :-)
