### ISSUE TITLE
Information in README.md

### ISSUE THREAD

**Issue by Cosmicore** [maestun/alis#8]
First of all, many thanks for your Silmarils depacker and ALIS engine restoration. It's amazing work and I keep my eye on its development.

In README.md you said that “Luckily, when checking the files present on the Silmarils Trilogy CD-ROM that I bought a few years back, I ran into some C files that were not part of the DOSBox sources (but had to be shipped, do to the GPL license), and looked like custom opcode tables.”

Unfortunately, I tried but was unable to identify this disk.

I have two different Ishar Trilogy CDs (I guess you meant it by “Silmarils Trilogy”, but I'm not sure), but I don't see anything like that inside. There are no C or DOSBox files on this disk, as it was issued in the days when DOSBox was not yet needed. I don't see any such С files on the GOG release either. I guess there is another CD in your possession.

Would you be so kind as to give more information about this CD? Who released it and when? Maybe you could show a picture of the CD or the cover? Many thanks in advance for any information.

**Comment by maestun** [comment]
Hello,
From memory, this disk contained *all* the Silmarils games and many tweaked DOSBox versions (each with its source code), so you're right, it wasn't named "Silmarils Trilogy", but "Silmarils Collection" instead.
I don't have the CDROM anymore, but I've found a copy of the disk on archive.org (Google is your friend ;) )

After install, the "magic" C files that helped me so much for starting reversing the virtual machine will be located in this archive (after install): "5 - dosbox 0.73-ishar deus delenter.zip", look into it for "src/routineTableFunctionsNames.c"

Cheers !
